---
- hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo
  
  tasks:
   - name: "安装Apache"
     apt: pkg=apache2 state=present

   - name: "安装git"
     apt: pkg=git state=present

   - name: "安装SQLite"
     apt: pkg={{ item }} state=present  update_cache=yes
     with_items:
        - sqlite3
        - libsqlite3-dev
   
   - name: Install MySQL client, server and related libraries
     apt: pkg={{ item }} state=latest
     with_items:
        - mysql-client
        - mysql-server
        - python-mysqldb

   - name: Start MySQL service
     service: name=mysql state=running enabled=yes

   - name: Setup MySQL root password
     mysql_user: name=root password=mysql host={{ item }} state=present 
     with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

   - name: "安装pip"
     apt: pkg={{ item }} state=present
     with_items:
        - python-pip
        - python-dev
        - build-essential
   
   - name: "安装Scrapy的依赖"
     apt: pkg={{ item }} state=present
     with_items:
        - libssl-dev
        - libffi-dev
        - python-dev
        - build-essential
   
   - name: check out workspace
     git: dest=/home/workspace repo=https://github.com/QinShelly/workspace.git
        update=yes
