
DISPLAY_FOLDER = 'Use Cases',ASSOCIATED_MEASURE_GROUP = 'STORE SALES',FORMAT_STRING = "#,##0.00",VISIBLE = 0;
DISPLAY_FOLDER = 'Use Cases',ASSOCIATED_MEASURE_GROUP = 'STORE SALES',FORMAT_STRING = "#,##0.00",VISIBLE = 0;
DISPLAY_FOLDER = 'Use Cases',ASSOCIATED_MEASURE_GROUP = 'STORE SALES',FORMAT_STRING = "#,##0.00",VISIBLE = 0;

DISPLAY_FOLDER = 'Use Cases',ASSOCIATED_MEASURE_GROUP = 'STORE SALES',FORMAT_STRING = "#,###",VISIBLE = 0;
DISPLAY_FOLDER = 'Use Cases',ASSOCIATED_MEASURE_GROUP = 'STORE SALES',FORMAT_STRING = "#,###",VISIBLE = 0;
DISPLAY_FOLDER = 'Use Cases',ASSOCIATED_MEASURE_GROUP = 'STORE SALES',FORMAT_STRING = "#,###",VISIBLE = 0;

