DELETE FROM RSI_VARIABLES WHERE VARIABLE_NAME= 'METRICS_BUILD_NUMBER';
INSERT INTO RSI_VARIABLES (VARIABLE_NAME,VARIABLE_VALUE) VALUES('METRICS_BUILD_NUMBER', '5.3');
go
truncate table [RSI_META_MEASURES_CORE_MIG]
go
BULK INSERT [RSI_META_MEASURES_CORE_MIG]
FROM '$(dataDir)\metrics\coremeasuresmig.csv'
WITH ( FIELDTERMINATOR = ',', ROWTERMINATOR = '\n' );
go
truncate table [RSI_META_MEASURES_CORE_AMOUNTTYPE]
go
BULK INSERT [RSI_META_MEASURES_CORE_AMOUNTTYPE]
FROM '$(dataDir)\metrics\coremeasuresamountype.csv'
WITH ( FIELDTERMINATOR = ',', ROWTERMINATOR = '\n' ,FIRSTROW=2);
go
truncate table [RSI_META_MEASURES_CORE]
go
BULK INSERT [RSI_META_MEASURES_CORE]
FROM '$(dataDir)\metrics\coremeasures.csv'
WITH ( FIELDTERMINATOR = ',', ROWTERMINATOR = '\n' ,FIRSTROW=2);
go
truncate table [RSI_META_MEASURES_RETAILER]

go
truncate table RSI_META_MEASURES_RETAILER_MAP
go

truncate table dbo.RSI_META_MEASURES_LY
go
BULK INSERT RSI_META_MEASURES_LY
FROM '$(dataDir)\metrics\lymetrics.csv'
WITH ( FIELDTERMINATOR = ',', ROWTERMINATOR = '\n' ,FIRSTROW=2);
GO

truncate table dbo.RSI_META_MEASURES_DESCRIPTION
go
BULK INSERT RSI_META_MEASURES_DESCRIPTION
FROM '$(dataDir)\metrics\retailermeasuresdescriptions.csv'
WITH ( FIELDTERMINATOR = '\t', ROWTERMINATOR = '\n' ,FIRSTROW=2);
GO

truncate table dbo.RSI_META_MEASURES_TYPE
go
BULK INSERT RSI_META_MEASURES_TYPE
FROM '$(dataDir)\metrics\measurestype.csv'
WITH ( FIELDTERMINATOR = '\t', ROWTERMINATOR = '\n' ,FIRSTROW=2);
GO

truncate table dbo.RSI_META_MEASURES
go
BULK INSERT RSI_META_MEASURES
FROM '$(dataDir)\metrics\measures.csv'
WITH ( FIELDTERMINATOR = '\t', ROWTERMINATOR = '\n' ,FIRSTROW=2);
GO
update [RSI_META_MEASURES] set [FORMAT_STRING] = ltrim(rtrim(REPLACE([FORMAT_STRING], '"', '')))
GO
truncate table dbo.RSI_META_MEASURES_RET
go
BULK INSERT RSI_META_MEASURES_RET
FROM '$(dataDir)\metrics\retailermeasuresx.csv'
WITH ( FIELDTERMINATOR = '\t', ROWTERMINATOR = '\n' ,FIRSTROW=2);
GO

update RSI_META_MEASURES_DESCRIPTION set MEASURE_NAME = ltrim(RTRIM(MEASURE_NAME))
where len(MEASURE_NAME) != len(ltrim(RTRIM(MEASURE_NAME)))

update RSI_META_MEASURES_CORE set MEASURE_NAME = ltrim(RTRIM(MEASURE_NAME))
where len(MEASURE_NAME) != len(ltrim(RTRIM(MEASURE_NAME)))

update RSI_META_MEASURES_LY set MEASURE_NAME = ltrim(RTRIM(MEASURE_NAME))
where len(MEASURE_NAME) != len(ltrim(RTRIM(MEASURE_NAME)))

update RSI_META_MEASURES_RET set MEASURE_NAME = ltrim(RTRIM(MEASURE_NAME))
where len(MEASURE_NAME) != len(ltrim(RTRIM(MEASURE_NAME)))

update RSI_META_MEASURES set MEASURE_NAME = ltrim(RTRIM(MEASURE_NAME))
where len(MEASURE_NAME) != len(ltrim(RTRIM(MEASURE_NAME)))

update RSI_META_MEASURES_TYPE set MEASURE_NAME = ltrim(RTRIM(MEASURE_NAME))
where len(MEASURE_NAME) != len(ltrim(RTRIM(MEASURE_NAME)))

update RSI_META_MEASURES_CORE_AMOUNTTYPE set MEASURE_NAME = ltrim(RTRIM(MEASURE_NAME))
where len(MEASURE_NAME) != len(ltrim(RTRIM(MEASURE_NAME)))

update RSI_META_MEASURES set MEASURE_NAME = ltrim(RTRIM(MEASURE_NAME))
where len(MEASURE_NAME) != len(ltrim(RTRIM(MEASURE_NAME)))

GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RSI_META_MEASURE_CONVERSION]') AND type in (N'U'))
BEGIN
	truncate table dbo.RSI_META_MEASURE_CONVERSION;
	INSERT INTO dbo.RSI_META_MEASURE_CONVERSION (RETAILER_NAME,CONVERSION_TYPE,[MEASURE_NAME],LOCATION_TYPE,CORE_MEASURE,PIT,REQUIRE_COUNT_MEASURE,REQUIRE_AVG)
	SELECT a.RETAILER_NAME, CONVERSION_TYPE, a.[MEASURE_NAME], LOCATION_TYPE, a.CORE_MEASURE,b.PIT,b.REQUIRE_COUNT_MEASURE,b.REQUIRE_AVG
	FROM (
		SELECT 1 CONVERSION_TYPE, [MEASURE_NAME],[DESCRIPTION], RETAILER_NAME, REPLACE(MEASURE_NAME, ' Cases', ' Units') CORE_MEASURE
		FROM [dbo].[RSI_META_MEASURES_DESCRIPTION]
		WHERE MEASURE_NAME like '%Cases' and [DESCRIPTION] = REPLACE(MEASURE_NAME, 'Cases', 'Units') + '/VENDOR_PACK_QTY'
	
		UNION ALL
		SELECT 2 CONVERSION_TYPE, [MEASURE_NAME],[DESCRIPTION], RETAILER_NAME , REPLACE(MEASURE_NAME, 'Cases', 'Units') CORE_MEASURE
		FROM [dbo].[RSI_META_MEASURES_DESCRIPTION]
		WHERE MEASURE_NAME like '%Cases' and [DESCRIPTION] like '%If VENDOR_PACK_QTY = DEFAULT_STORE_PACK_QTY%/VENDOR_PACK_QTY%'

		UNION ALL
		SELECT 3 CONVERSION_TYPE, [MEASURE_NAME] ,[DESCRIPTION], RETAILER_NAME, REPLACE(MEASURE_NAME, ' Units', ' Cases') CORE_MEASURE
		FROM [dbo].[RSI_META_MEASURES_DESCRIPTION]
		WHERE  MEASURE_NAME like '%Units' and [DESCRIPTION] = REPLACE(MEASURE_NAME, 'Units', 'Cases') + '*VENDOR_PACK_QTY'
	
		UNION ALL
		SELECT 4 CONVERSION_TYPE, [MEASURE_NAME],[DESCRIPTION], RETAILER_NAME, REPLACE(MEASURE_NAME, ' Units', ' Cases') CORE_MEASURE
		FROM [dbo].[RSI_META_MEASURES_DESCRIPTION]
		WHERE MEASURE_NAME like '%Units' and [DESCRIPTION] like '%If VENDOR_PACK_QTY = DEFAULT_STORE_PACK_QTY%*VENDOR_PACK_QTY%'
	
		UNION ALL
		SELECT 5 CONVERSION_TYPE, replace([MEASURE_NAME], ' Units', ' Equivalent Units'),'', RETAILER_NAME, [MEASURE_NAME] CORE_MEASURE
		FROM [dbo].RSI_META_MEASURES_CORE
		WHERE REQUIRE_EQUI_CONVERSION = 1 and RETAILER_NAME != '*'
  
	) a
	  join [dbo].RSI_META_MEASURES_CORE b on b.MEASURE_NAME = a.CORE_MEASURE and (b.RETAILER_NAME = '*' or a.RETAILER_NAME = b.RETAILER_NAME)
	  order by a.RETAILER_NAME, LOCATION_TYPE,CONVERSION_TYPE,a.MEASURE_NAME
  END 
  